KS-6-1
KinCadeFoster/KotlinSprint pull request #28
Opened 2024-04-03 17:39 UTC by KinCadeFoster

- Логика проверки логина и пароля

2024-04-04 07:42 UTC, ievetrovdev requested changes

2024-04-04 07:42 UTC, ievetrovdev commented on src/main/kotlin/lesson_6/lesson6_task1.kt
> +        if (login == enterLogin && password == enterPassword) {
можно чуть упростить если использовать do while и проверку делать в while

2024-04-04 14:48 UTC, ievetrovdev requested changes

2024-04-04 14:48 UTC, ievetrovdev commented on src/main/kotlin/lesson_6/lesson6_task1.kt
> +        if (login == enterLogin && password == enterPassword) {
Смысл верен, но теперь этот if лишний, дважды проверяешь одно и тоже

2024-04-04 14:54 UTC, KinCadeFoster commented on src/main/kotlin/lesson_6/lesson6_task1.kt
> +        if (login == enterLogin && password == enterPassword) {
Не совсем понял, а как мы реализуем проверку на корректность ввода?

2024-04-07 04:38 UTC, ievetrovdev requested changes

2024-04-07 04:38 UTC, ievetrovdev commented on src/main/kotlin/lesson_6/lesson6_task1.kt
> +        if (login != enterLogin && password != enterPassword)
Сейчас уже почти идеально. Можно вообще опустить это, но если сильно хочешь сохранить текст, то можно записать результат в переменную и использовать в if и while уже ее

2024-04-08 07:04 UTC, ievetrovdev approved these changes

2024-04-08 10:14 UTC, merged