KS-6-5
KinCadeFoster/KotlinSprint pull request #32
Opened 2024-04-03 18:47 UTC by KinCadeFoster

- Написание капчи

2024-04-04 07:50 UTC, ievetrovdev requested changes

2024-04-04 07:50 UTC, ievetrovdev commented on src/main/kotlin/lesson_6/lesson6_task5.kt
> +            while (true) {
Не лучшее решение использовать вложенные циклы, да логика перегружена условиями, лучше переделать на блоки используя советы из предыдущих задач

2024-04-05 07:41 UTC, ievetrovdev requested changes

2024-04-05 07:41 UTC, ievetrovdev commented on src/main/kotlin/lesson_6/lesson6_task5.kt
> +        if (login == enterLogin && password == enterPassword) {
Опять лишний if, тоже самое в while происходит

2024-04-05 07:41 UTC, ievetrovdev commented on src/main/kotlin/lesson_6/lesson6_task5.kt
> +            userLogin()
Стало читаемей, но вложений цикл то остался, хоть и в виде вызова функции. можно же вынести эту функцию выше цикла, так будет оптимизированией и логичней

2024-04-06 16:16 UTC, KinCadeFoster commented
Из задачи не совсем понятно, в начале мы капчу проходим или авторизацию?
Если авторизацию, то переделаный код верный, если капчу, то не верный и не совсем понятно как вынести это из цикла

2024-04-07 04:41 UTC, ievetrovdev approved these changes
вообще по заданию должна быть только капча, но раз ты захотел сделать все, то они должны проходить последовательно. Вообще старайся избегать вложенных циклов, они очень ресурсозатратны

2024-04-07 05:26 UTC, merged