KS-7-5
KinCadeFoster/KotlinSprint pull request #37
Opened 2024-04-04 17:03 UTC by KinCadeFoster

- Генерация более сложного пароля

2024-04-05 16:20 UTC, ievetrovdev requested changes

2024-04-05 16:20 UTC, ievetrovdev commented on src/main/kotlin/lesson_7/lesson7_task5.kt
> +    val charsLow = 'A'..'z'
для строчных букв диапазон должен быть `'a'..'z'`

2024-04-05 16:20 UTC, ievetrovdev commented on src/main/kotlin/lesson_7/lesson7_task5.kt
> +        if (getRandomNumber() % 2 == 0) password.append(chars.random())
символы же не должны чередоваться в пароле судя по условию

2024-04-05 16:20 UTC, ievetrovdev commented on src/main/kotlin/lesson_7/lesson7_task5.kt
> +    for (i in 1..passwordLength) {
Есть вероятность, что рандомайзер при генерации пароля упустит один или несколько типов символов. 
Стоит изменить подход. Например, сперва добавлять обязательные символы, затем рандомно оставшиеся из общего набора.

2024-04-05 16:20 UTC, ievetrovdev commented on src/main/kotlin/lesson_7/lesson7_task5.kt
> +    val numbers = 0..9
числа также можно добавить к общему набору

2024-04-06 16:19 UTC, KinCadeFoster commented on src/main/kotlin/lesson_7/lesson7_task5.kt
> +        if (getRandomNumber() % 2 == 0) password.append(chars.random())
они и не чередуются, мы получаем рандомное число и на основе его получаем остаток от деления и дальше как повезет

2024-04-06 16:24 UTC, KinCadeFoster commented on src/main/kotlin/lesson_7/lesson7_task5.kt
> +    for (i in 1..passwordLength) {
это не упростит подбор пароля? может логичнее проверять наличие обязательных символов получившегося пароля и если не подошел, то отбраколвывать его и повторно генерить?

2024-04-07 05:39 UTC, ievetrovdev approved these changes

2024-04-07 17:32 UTC, merged