9-5
KinCadeFoster/KotlinSprint pull request #47
Opened 2024-04-11 20:27 UTC by KinCadeFoster

- парсинг и вывод ингредиентов

2024-04-12 07:42 UTC, ievetrovdev requested changes

2024-04-12 07:42 UTC, ievetrovdev commented on src/main/kotlin/lesson_9/lesson9_task5.kt
> +    val sortedIngredients = ingredients.sorted().toMutableList()
Хорошо! но повторов такой подход не позволит избежать. посмотри или вспомни какая коллекция не умеет хранить повторы?
Вот в нее можно превратить проинициализированный введенными значениями список.

2024-04-12 09:12 UTC, KinCadeFoster commented on src/main/kotlin/lesson_9/lesson9_task5.kt
> +    val sortedIngredients = ingredients.sorted().toMutableList()
может я чего то не понимаю, но намек на mutableSetOf, но он и применен на этапе формирования списка, что исключает дубли на этапе, когда я уже преобразовываю в toMutableList.  Как следствие, никаких дублей быть уже не может.
Сам же Set не дает гарантии порядка вывода элементов, что как следствие, требует изменения логики. Или я что то не понял?

2024-04-13 05:48 UTC, ievetrovdev approved these changes

2024-04-13 05:48 UTC, ievetrovdev commented on src/main/kotlin/lesson_9/lesson9_task5.kt
> +    val sortedIngredients = ingredients.sorted().toMutableList()
да, ты прав, не заметил что у тебя сет уже используется)

2024-04-13 15:47 UTC, merged