16-2
KinCadeFoster/KotlinSprint pull request #80
Opened 2024-05-15 10:17 UTC by KinCadeFoster

- расчет площади и радиуса круга

2024-05-15 20:45 UTC, ievetrovdev requested changes

2024-05-15 20:45 UTC, ievetrovdev commented on src/main/kotlin/lesson_16/lesson16_task2.kt
> +    private val Pi = 3.14
Давай еще сделаем ее const, тк это все таки постоянное число.

2024-05-15 20:45 UTC, ievetrovdev commented on src/main/kotlin/lesson_16/lesson16_task2.kt
> +        return Pi * radius * radius
Тут можно использовать Котлин экстеншн функцию для возведения в степень.

2024-05-15 20:45 UTC, ievetrovdev commented on src/main/kotlin/lesson_16/lesson16_task2.kt
> +    println(circle.getAreaCircle())
Лучше добавить в консольный вывод пояснение какое значение выводится (Circumference:,  Area:)

2024-05-16 15:27 UTC, ievetrovdev approved these changes
return Pi * radius * radius, тут можно было использовать Котлин экстеншн функцию для возведения в степень.

2024-05-16 16:16 UTC, KinCadeFoster commented
> return Pi * radius * radius, тут можно было использовать функцию экстеншн Котлина для возведения в степень.

пропустил этот комментарий, добавил return PI * radius.pow(2)

2024-05-16 16:17 UTC, merged