17-3
KinCadeFoster/KotlinSprint pull request #86
Opened 2024-05-16 17:11 UTC by KinCadeFoster

- Реализация скрытых папок

2024-05-17 04:47 UTC, ievetrovdev requested changes

2024-05-17 04:47 UTC, ievetrovdev commented on src/main/kotlin/lesson_17/lesson17_task3.kt
> +class Folder(folderName: String, numberFiles: Int, folderSecurity: Boolean) {
Boolean поле корректнее называть как бы “отвечая на вопрос да/нет”. Например, isSecret.

2024-05-17 04:47 UTC, ievetrovdev commented on src/main/kotlin/lesson_17/lesson17_task3.kt
> +    private val security = folderSecurity
Мы можем использовать `folderSecurity` напрямую, зачем создавать еще одно свойство?

2024-05-17 04:47 UTC, ievetrovdev commented on src/main/kotlin/lesson_17/lesson17_task3.kt
> +    fun folderInfo() {
Названия функций должны быть в инфинитиве

2024-05-17 10:31 UTC, KinCadeFoster commented on src/main/kotlin/lesson_17/lesson17_task3.kt
> +    private val security = folderSecurity
Хороший вопрос, полагаю что сначала просто создал переменные, потом уже по задаче смотрел где нужны сеттеры и геттеры)

2024-05-18 07:28 UTC, ievetrovdev approved these changes

2024-05-18 12:33 UTC, merged